services:
  tofu-vtubia:
    image: ghcr.io/mayopickle/tofu-vtubia:master
    container_name: tofu-vtubia
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/songs.db:/app/songs.db
    env_file:
      - ./backend/.env
    networks:
      - tofu-network

  db:
    image: postgres:14-alpine
    container_name: tofu-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tofu_music
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tofu-network

networks:
  tofu-network:
    driver: bridge

volumes:
  postgres_data: 